import { Effect, Layer } from "effect";

import { WeatherProvider } from "@/domain/ports";

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

export const DemoWeatherProviderLive = Layer.succeed(WeatherProvider, {
  fetchRecentStorms: () =>
    Effect.succeed([
      {
        id: crypto.randomUUID(),
        source: "demo",
        sourceEventId: "demo-hail-dfw-1",
        eventType: "hail" as const,
        occurredAt: hoursAgo(2),
        lat: 32.7767,
        lng: -96.797,
        city: "Dallas",
        region: "TX",
        severity: "severe" as const,
        hailSize: 1.75,
        windSpeed: null,
        createdAt: new Date().toISOString(),
      },
      {
        id: crypto.randomUUID(),
        source: "demo",
        sourceEventId: "demo-wind-frisco-1",
        eventType: "wind" as const,
        occurredAt: hoursAgo(4),
        lat: 33.1507,
        lng: -96.8236,
        city: "Frisco",
        region: "TX",
        severity: "moderate" as const,
        hailSize: null,
        windSpeed: 62,
        createdAt: new Date().toISOString(),
      },
      {
        id: crypto.randomUUID(),
        source: "demo",
        sourceEventId: "demo-hail-fortworth-1",
        eventType: "hail" as const,
        occurredAt: hoursAgo(9),
        lat: 32.7555,
        lng: -97.3308,
        city: "Fort Worth",
        region: "TX",
        severity: "moderate" as const,
        hailSize: 1.25,
        windSpeed: null,
        createdAt: new Date().toISOString(),
      },
      {
        id: crypto.randomUUID(),
        source: "demo",
        sourceEventId: "demo-wind-waco-1",
        eventType: "wind" as const,
        occurredAt: hoursAgo(12),
        lat: 31.5493,
        lng: -97.1467,
        city: "Waco",
        region: "TX",
        severity: "light" as const,
        hailSize: null,
        windSpeed: 46,
        createdAt: new Date().toISOString(),
      },
      {
        id: crypto.randomUUID(),
        source: "demo",
        sourceEventId: "demo-hail-okc-1",
        eventType: "hail" as const,
        occurredAt: hoursAgo(20),
        lat: 35.4676,
        lng: -97.5164,
        city: "Oklahoma City",
        region: "OK",
        severity: "severe" as const,
        hailSize: 2,
        windSpeed: null,
        createdAt: new Date().toISOString(),
      },
    ]),
});
